### ISSUE TITLE
crash when click the downloading icon

### ISSUE THREAD

**Issue by wenqin-231** [alexjlockwood/adp-delightful-details#8]
`07-28 10:41:29.361 6814-6814/com.alexjlockwood.example.delight E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: com.alexjlockwood.example.delight, PID: 6814
                                                                                 java.lang.IllegalArgumentException: no valueFrom or no valueTo
                                                                                     at android.support.graphics.drawable.AnimatorInflaterCompat.parseAnimatorFromTypeArray(AnimatorInflaterCompat.java:361)
                                                                                     at android.support.graphics.drawable.AnimatorInflaterCompat.loadAnimator(AnimatorInflaterCompat.java:815)
                                                                                     at android.support.graphics.drawable.AnimatorInflaterCompat.loadObjectAnimator(AnimatorInflaterCompat.java:790)
                                                                                     at android.support.graphics.drawable.AnimatorInflaterCompat.createAnimatorFromXml(AnimatorInflaterCompat.java:443)
                                                                                     at android.support.graphics.drawable.AnimatorInflaterCompat.createAnimatorFromXml(AnimatorInflaterCompat.java:454)
                                                                                     at android.support.graphics.drawable.AnimatorInflaterCompat.createAnimatorFromXml(AnimatorInflaterCompat.java:417)
                                                                                     at android.support.graphics.drawable.AnimatorInflaterCompat.loadAnimator(AnimatorInflaterCompat.java:126)
                                                                                     at android.support.graphics.drawable.AnimatorInflaterCompat.loadAnimator(AnimatorInflaterCompat.java:113)
                                                                                     at android.support.graphics.drawable.AnimatorInflaterCompat.loadAnimator(AnimatorInflaterCompat.java:96)
                                                                                     at android.support.graphics.drawable.AnimatedVectorDrawableCompat.inflate(AnimatedVectorDrawableCompat.java:485)
                                                                                     at android.support.graphics.drawable.AnimatedVectorDrawableCompat.createFromXmlInner(AnimatedVectorDrawableCompat.java:253)
                                                                                     at android.support.graphics.drawable.AnimatedVectorDrawableCompat.create(AnimatedVectorDrawableCompat.java:233)
                                                                                     at com.alexjlockwood.example.delight.DownloadingActivity.swapAnimation(DownloadingActivity.java:60)
                                                                                     at com.alexjlockwood.example.delight.DownloadingActivity.access$000(DownloadingActivity.java:15)
                                                                                     at com.alexjlockwood.example.delight.DownloadingActivity$1.run(DownloadingActivity.java:47)
                                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:158)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

the device is Samsung  in Android 6.0

**Comment by alexjlockwood** [comment]
I disabled aapt2 in the `gradle.properties` file... should be fixed now.
