### ISSUE TITLE
Animated Fingerprint icon causes crash after upgrading to gradle build tools 3.0.0-beta4

### ISSUE THREAD

**Issue by luckyhandler** [alexjlockwood/adp-delightful-details#9]
`java.lang.RuntimeException: Unable to start activity ComponentInfo{___}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class ImageView
                                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
                                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                                   at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                                                Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class ImageView
                                                                                Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class ImageView
                                                                                Caused by: android.content.res.Resources$NotFoundException: Drawable ___/asl_fingerprint with resource ID #0x7f080080
                                                                                Caused by: java.lang.RuntimeException: Unknown animator name: attr`

the attr - Attribute seems to be not supported any more...

**Comment by nickbutcher** [comment]
This is a known issue with aapt2 (which is used by default by AGP3). It's filed internally but not fixed yet.

**Comment by luckyhandler** [comment]
Can you provide a link to this issue or is it not public?

**Comment by luckyhandler** [comment]
The link is e.g. https://twitter.com/androidstudio/status/875311569219006464

**Comment by alexjlockwood** [comment]
I disabled aapt2 for now in the `gradle.properties`... someone (ahem @nickbutcher :P) remind me to remove that once the bug is fixed. :)
